name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_coding_style:
    if: ${{ "$GITHUB_REPOSITORY" == "morgangch/chocolatine" }}
    name: "Use coding_style_checker"
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - id: check_coding_style
        run: |
          check.sh $(pwd) $(pwd)

  push_to_mirror:
    needs: check_coding_style
    if: ${{ github.event_name == 'push' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}
          ssh_private_key: 
            ${{ secrets.SSH_PRIVATE_KEY }}