name: chocolatine

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
      - uses: actions/checkout@v4

      - name: Push to destination repository
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target-repo-url: git@github.com:EpitechPromo2028/B-DOP-200-MPL-2-1-chocolatine-morgan.guichard
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}